name: urban-resilience
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - rasterio
  - fiona
  - pyproj
  - shapely
  - osmnx
  - xgboost
  - scikit-learn
  - shap
  - mlflow
  - joblib
  - requests
  - fastapi
  - uvicorn
  - pydantic
  - streamlit
  - folium
  - plotly
  - pytest
  - jupyter
  - notebook
  - pip
  - pip:
      - streamlit-folium
      - earthengine-api
      - fastparquet
